export default [
    'Sed cursus ante dapibus diam.',
    'Lorem ipsum dolor sit amet',
    'Consectetur adipiscing elit.',
    'Integer nec odio.',
    'Praesent libero.',
    'Praesent libero.',
    'Praesent libero.',
    'Praesent libero.',
    'Praesent libero.',
    'Praesent libero.',
    'Praesent libero.',
    'Praesent libero.',
    'Praesent libero.',
    'Praesent libero.',
    'Praesent libero.',
    'Praesent libero.',
    'Praesent libero.',
    'Praesent libero.',
    'Praesent libero.',
    'Sed nisi. '
]